Feat: Do not require specification of tox environments
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/workflows/testing.yaml b/.github/workflows/testing.yaml
--- a/.github/workflows/testing.yaml
+++ b/.github/workflows/testing.yaml
@@ -3,7 +3,7 @@
 # SPDX-FileCopyrightText: 2025 The Linux Foundation
 
 # Action test/validation workflow
-name: "Test GitHub Action 🧪"
+name: "GitHub Action"
 
 # yamllint disable-line rule:truthy
 on:
@@ -15,10 +15,13 @@ on:
 
 permissions: {}
 
+env:
+  python_version: "3.12"
+
 jobs:
   ### Test the GitHub Action in this Repository ###
   tests:
-    name: "Test local GitHub Action"
+    name: "Run Tests 🧪"
     runs-on: ubuntu-24.04
     permissions:
       contents: read
@@ -41,46 +44,53 @@ jobs:
         with:
           path_prefix: "test-python-project/"
           tox_build: false
+          python_version: ${{ env.python_version }}
 
       # Perform Python project standard tests
-      - name: "Run action: ${{ github.repository }} [Regular Tests]"
+      - name: "Run action: ${{ github.repository }} [PYTEST]"
         uses: ./
         with:
           python_version: "${{ steps.build.outputs.build_python_version }}"
           path_prefix: "test-python-project/"
           tests_path: "tests"
 
-      # Perform Python project failing tests
-      - name: "Run action: ${{ github.repository }} [Failing Test]"
+      # Perform Python project standard tests
+      - name: "Run action: ${{ github.repository }} [TOX]"
         uses: ./
-        # Test permit failure using continue-on-error
+        with:
+          python_version: "${{ steps.build.outputs.build_python_version }}"
+          path_prefix: "test-python-project/"
+          tests_path: "tests"
+          tox_tests: "true"
+          report_artefact: false
+
+      # Perform Python project failing tests
+      - name: "Run action: ${{ github.repository }} [Test Failure]"
+        uses: ./
+        with:
+          python_version: "${{ steps.build.outputs.build_python_version }}"
+          path_prefix: "test-python-project/"
+          report_artefact: false
+          # Test permit failure using action input
+          tests_path: "tests_fail"
+          permit_fail: true
+
+      # Perform Python project failing tests
+      - name: "Run action: ${{ github.repository }} [Test Failure]"
+        id: tests-fail
+        uses: ./
         continue-on-error: true
         with:
           python_version: "${{ steps.build.outputs.build_python_version }}"
           path_prefix: "test-python-project/"
-          tests_path: "tests_fail"
           report_artefact: false
-
-      # Perform Python project failing tests
-      - name: "Run action: ${{ github.repository }} [Failing Test]"
-        uses: ./
-        with:
-          python_version: "${{ steps.build.outputs.build_python_version }}"
-          path_prefix: "test-python-project/"
-          tests_path: "tests_fail"
           # Test permit failure using action input
-          permit_fail: true
-          report_artefact: false
+          tests_path: "tests_fail"
 
-      # Enable when test-python-project tests location is fixed in tox.ini
-
-      # Perform Python project testing with tox
-      # - name: "Run action: ${{ github.repository }} [TOX Tests]"
-      #   uses: ./
-      #   with:
-      #     python_version: "${{ steps.build.outputs.build_python_version }}"
-      #     path_prefix: "test-python-project/"
-      #     report_artefact: false
-      #     tox_tests: true
-      #     # Do not run TOX linting when "no-commit-to-branch" enabled
-      #     tox_envs: "tests"
+      - name: "Validate previous step failure"
+        if: steps.tests-fail.outcome == 'success'
+        shell: bash
+        run: |
+          # Check previous step failure
+          echo "Error: previous step should have failed ❌"
+          exit 1
diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -41,7 +41,6 @@ inputs:
     description: "Space separated list of tox environments to run"
     required: false
     type: string
-    default: "lint tests"
 
 runs:
   using: "composite"
@@ -75,12 +74,13 @@ runs:
           echo "Warning: test failures will be permitted ⚠️"
         fi
 
+        # Testing with TOX
         if [ "f${{ inputs.TOX_TESTS }}" = "ftrue" ]; then
           echo "Using tox to perform tests 💬"
           if [ -z "${{ inputs.TOX_ENVS }}" ]; then
-            echo "Error: no tox environments were specified ❌"; exit 1
+            echo "Warning: testing with tox but no environments specified ⚠️"
           else
-            echo "Tox environments: ${{ inputs.TOX_ENVS }} 💬"
+            echo "Testing with tox; environments: ${{ inputs.TOX_ENVS }} 💬"
           fi
         fi
 
@@ -132,10 +132,14 @@ runs:
         # Performing tests [tox]
         echo "Installing: tox ⬇️"
         pip install --disable-pip-version-check -q tox
-        for ENV in ${{ inputs.TOX_ENVS }}; do
-          echo "Running: tox -c ${{ env.path_prefix }}/tox.ini -e $ENV 💬"
-          tox -c ${{ env.path_prefix }}/tox.ini -e "$ENV"
-        done
+        if [ -z "${{ inputs.TOX_ENVS }}" ]; then
+          for ENV in ${{ inputs.TOX_ENVS }}; do
+            echo "Running: tox -c ${{ env.path_prefix }}/tox.ini -e $ENV 💬"
+            tox -c ${{ env.path_prefix }}/tox.ini -e "$ENV"
+          done
+        else
+          echo "Running: tox -c ${{ env.path_prefix }}/tox.ini 💬"
+        fi
 
     - name: "Tests and coverage report [pytest]"
       if: inputs.TOX_TESTS != 'true'
@@ -173,7 +177,12 @@ runs:
           zip -r test_coverage_report-${{ inputs.PYTHON_VERSION }}.zip \
             coverage_report
         else
-          echo "No coverage report directory exists"
+          if [ "f${{ inputs.permit_fail }}" = 'ftrue' ]; then
+            echo "Error: coverage report requested but no content found ⚠️"
+          else
+            echo "Error: coverage report requested but no content found ❌"
+            exit 1
+          fi
         fi
 
     - name: "Upload test/coverage report"
